name: Dependencies - Arm32v7

on:
  pull_request:
    branches:
      - depends
    paths:
      - 'depends/**'
  push:
    branches:
      - depends
    paths:
      - 'depends/**'

env:
  OS: arm32v7
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts
  
jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1

    - name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${OS}

    - name: Build the Dependencies
      run: cd depends && make HOST=arm-linux-gnueabihf -j2

    - name: Tar Up the Dependencies
      run: |
          if [[ ! -e ${{ GITHUB.WORKSPACE }}/depends_temp ]]; then mkdir -p ${{ GITHUB.WORKSPACE }}/depends_temp; fi
          cd ${{ GITHUB.WORKSPACE }}/depends && tar zcf ${{ GITHUB.WORKSPACE }}/depends_temp/raven-arm32v7-dependencies.tar.gz .
          cd ${{ GITHUB.WORKSPACE }}/depends_temp
          if [[ -e raven-arm32v7-dependencies.tar.gz ]]; then sha256sum raven-arm32v7-dependencies.tar.gz > SHASUM; else echo "no dependency tar file found"; fi